// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isDataURI.gohtml

package templates

import (
	"io"
	"strings"
)

// IsDataURI generates templates/isDataURI.gohtml
func IsDataURI() string {
	var _b strings.Builder
	RenderIsDataURI(&_b)
	return _b.String()
}

// RenderIsDataURI render templates/isDataURI.gohtml
func RenderIsDataURI(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isDataURI(ref string) bool {\n    uri := strings.SplitN(ref, \",\", 2)\n\n\tif len(uri) != 2 {\n\t\treturn false\n\t}\n\n\tif !dataURIRegex.MatchString(uri[0]) {\n\t\treturn false\n\t}\n\n\treturn base64Regex.MatchString(uri[1])\n}")

}
