// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isEthereumAddress.gohtml

package templates

import (
	"io"
	"strings"
)

// IsEthereumAddress generates templates/isEthereumAddress.gohtml
func IsEthereumAddress() string {
	var _b strings.Builder
	RenderIsEthereumAddress(&_b)
	return _b.String()
}

// RenderIsEthereumAddress render templates/isEthereumAddress.gohtml
func RenderIsEthereumAddress(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isEthereumAddress(ref string) bool {\n\taddress := ref\n\tif !ethAddressRegex.MatchString(address) {\n\t\treturn false\n\t}\n\n\tif ethaddressRegexUpper.MatchString(address) || ethAddressRegexLower.MatchString(address) {\n\t\treturn true\n\t}\n\n\t// checksum validation is blocked by https://github.com/golang/crypto/pull/28\n\n\treturn true\n}")

}
