// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isHTML.gohtml

package templates

import (
	"io"
	"strings"
)

// IsHTML generates templates/isHTML.gohtml
func IsHTML() string {
	var _b strings.Builder
	RenderIsHTML(&_b)
	return _b.String()
}

// RenderIsHTML render templates/isHTML.gohtml
func RenderIsHTML(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isURLEncoded(source string) bool {\n\treturn uRLEncodedRegex.MatchString(source)\n}\n\nfunc isHTMLEncoded(source string) bool {\n\treturn hTMLEncodedRegex.MatchString(source)\n}\n\nfunc isHTML(source string) bool {\n\treturn hTMLRegex.MatchString(source)\n}")

}
