// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isISBN10.gohtml

package templates

import (
	"io"
	"strings"
)

// IsISBN10 generates templates/isISBN10.gohtml
func IsISBN10() string {
	var _b strings.Builder
	RenderIsISBN10(&_b)
	return _b.String()
}

// RenderIsISBN10 render templates/isISBN10.gohtml
func RenderIsISBN10(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isISBN10(ref string) bool {\n\ts := strings.Replace(strings.Replace(ref, \"-\", \"\", 3), \" \", \"\", 3)\n\n\tif !iSBN10Regex.MatchString(s) {\n\t\treturn false\n\t}\n\n\tvar checksum int32\n\tvar i int32\n\n\tfor i = 0; i < 9; i++ {\n\t\tchecksum += (i + 1) * int32(s[i]-'0')\n\t}\n\n\tif s[9] == 'X' {\n\t\tchecksum += 10 * 10\n\t} else {\n\t\tchecksum += 10 * int32(s[9]-'0')\n\t}\n\n\treturn checksum%11 == 0\n}")

}
