// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isISBN13.gohtml

package templates

import (
	"io"
	"strings"
)

// IsISBN13 generates templates/isISBN13.gohtml
func IsISBN13() string {
	var _b strings.Builder
	RenderIsISBN13(&_b)
	return _b.String()
}

// RenderIsISBN13 render templates/isISBN13.gohtml
func RenderIsISBN13(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isISBN13(ref string) bool {\n    s := strings.Replace(strings.Replace(ref, \"-\", \"\", 4), \" \", \"\", 4)\n\n\tif !iSBN13Regex.MatchString(s) {\n\t\treturn false\n\t}\n\n\tvar checksum int32\n\tvar i int32\n\n\tfactor := []int32{1, 3}\n\n\tfor i = 0; i < 12; i++ {\n\t\tchecksum += factor[i%2] * int32(s[i]-'0')\n\t}\n\n\treturn (int32(s[12]-'0'))-((10-(checksum%10))%10) == 0\n}")

}
