// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isSSN.gohtml

package templates

import (
	"io"
	"strings"
)

// IsSSN generates templates/isSSN.gohtml
func IsSSN() string {
	var _b strings.Builder
	RenderIsSSN(&_b)
	return _b.String()
}

// RenderIsSSN render templates/isSSN.gohtml
func RenderIsSSN(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isSSN(ref string) bool {\n\tif len(ref) != 11 {\n\t\treturn false\n\t}\n\n\treturn sSNRegex.MatchString(ref)\n}")

}
