// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isUrnRFC2141.gohtml

package templates

import (
	"io"
	"strings"
)

// IsUrnRFC2141 generates templates/isUrnRFC2141.gohtml
func IsUrnRFC2141() string {
	var _b strings.Builder
	RenderIsUrnRFC2141(&_b)
	return _b.String()
}

// RenderIsUrnRFC2141 render templates/isUrnRFC2141.gohtml
func RenderIsUrnRFC2141(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isUrnRFC2141(ref string) bool {\n\ts := ref\n\t_, match := urn.Parse([]byte(s))\n    return match\n}")

}
