// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/isURI.gohtml

package templates

import (
	"io"
	"strings"
)

// IsURI generates templates/isURI.gohtml
func IsURI() string {
	var _b strings.Builder
	RenderIsURI(&_b)
	return _b.String()
}

// RenderIsURI render templates/isURI.gohtml
func RenderIsURI(_buffer io.StringWriter) {
	_buffer.WriteString("\nfunc isURI(ref string) bool {\n\ts := ref\n\n\t// checks needed as of Go 1.6 because of change https://github.com/golang/go/commit/617c93ce740c3c3cc28cdd1a0d712be183d0b328#diff-6c2d018290e298803c0c9419d8739885L195\n\t// emulate browser and strip the '#' suffix prior to validation. see issue-#237\n\tif i := strings.Index(s, \"#\"); i > -1 {\n\t\ts = s[:i]\n\t}\n\n\tif len(s) == 0 {\n\t\treturn false\n\t}\n\n\t_, err := url.ParseRequestURI(s)\n\n\treturn err == nil\n}")

}
