// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/errors/nil.gohtml

package errors

import (
	"github.com/lab259/go-my-ast-hurts"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Nil generates templates/errors/nil.gohtml
func Nil(field *myasthurts.Field, tag myasthurts.TagParam, value interface{}) string {
	var _b strings.Builder
	RenderNil(&_b, field, tag, value)
	return _b.String()
}

// RenderNil render templates/errors/nil.gohtml
func RenderNil(_buffer io.StringWriter, field *myasthurts.Field, tag myasthurts.TagParam, value interface{}) {
	_buffer.WriteString("\nif ")
	_buffer.WriteString(gorazor.HTMLEscape(value))
	_buffer.WriteString(" == nil {\n\terrs = append(errs, NewError(\"")
	_buffer.WriteString(gorazor.HTMLEscape(field.Name))
	_buffer.WriteString("\", \"")
	_buffer.WriteString(gorazor.HTMLEscape(tag.Value))
	_buffer.WriteString("\"))\n}")

}
