// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/errors/number.gohtml

package errors

import (
	"github.com/lab259/go-my-ast-hurts"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Number generates templates/errors/number.gohtml
func Number(filter string, field *myasthurts.Field, tag myasthurts.TagParam, value interface{}) string {
	var _b strings.Builder
	RenderNumber(&_b, filter, field, tag, value)
	return _b.String()
}

// RenderNumber render templates/errors/number.gohtml
func RenderNumber(_buffer io.StringWriter, filter string, field *myasthurts.Field, tag myasthurts.TagParam, value interface{}) {
	_buffer.WriteString("\nif ")
	_buffer.WriteString(gorazor.HTMLEscape(filter))
	_buffer.WriteString(" (")
	_buffer.WriteString(gorazor.HTMLEscape(value))
	_buffer.WriteString(") {\n\terrs = append(errs, NewError(\"")
	_buffer.WriteString(gorazor.HTMLEscape(field.Name))
	_buffer.WriteString("\", \"")
	_buffer.WriteString(gorazor.HTMLEscape(tag.Value))
	_buffer.WriteString("\"))\n}")

}
