// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/rules/condition.gohtml

package rules

import (
	"github.com/lab259/go-my-ast-hurts"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Condition generates templates/rules/condition.gohtml
func Condition(condition string, field *myasthurts.Field, tag myasthurts.TagParam) string {
	var _b strings.Builder
	RenderCondition(&_b, condition, field, tag)
	return _b.String()
}

// RenderCondition render templates/rules/condition.gohtml
func RenderCondition(_buffer io.StringWriter, condition string, field *myasthurts.Field, tag myasthurts.TagParam) {
	_buffer.WriteString("\n\nif ")
	_buffer.WriteString((condition))
	_buffer.WriteString(" {\n\terrs = append(errs, NewError(\"")
	_buffer.WriteString(gorazor.HTMLEscape(field.Name))
	_buffer.WriteString("\", \"")
	_buffer.WriteString(gorazor.HTMLEscape(tag.Value))
	_buffer.WriteString("\"))\n}")

}
