// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/rules/conditionWithValue.gohtml

package rules

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// ConditionWithValue generates templates/rules/conditionWithValue.gohtml
func ConditionWithValue(condition string, field string, tag string) string {
	var _b strings.Builder
	RenderConditionWithValue(&_b, condition, field, tag)
	return _b.String()
}

// RenderConditionWithValue render templates/rules/conditionWithValue.gohtml
func RenderConditionWithValue(_buffer io.StringWriter, condition string, field string, tag string) {
	_buffer.WriteString("\n\nif ")
	_buffer.WriteString((condition))
	_buffer.WriteString(" {\n\terrs = append(errs, NewError(\"")
	_buffer.WriteString(gorazor.HTMLEscape(field))
	_buffer.WriteString("\", \"")
	_buffer.WriteString(gorazor.HTMLEscape(tag))
	_buffer.WriteString("\"))\n}")

}
